### ISSUE TITLE
Installing uuid==1.30

### ISSUE THREAD

**Issue by tminakov** [robooo/robotframework-ConfluentKafkaLibrary#10]
The `setup.py` specifies uuid==1.30, and pip installs this library: https://pypi.org/project/uuid/#history - but it shadows the module `uuid` from the standard library - https://docs.python.org/3/library/uuid.html (it's also in py2). 

And in executing tests, some other modules that are using `uuid` (I have a couple that import it, and also 3rd party libraries like boto3 do it) are throwing an error:

```
Importing test library 'C:\xxx\AWSLibrary.py' failed: SyntaxError: invalid syntax (uuid.py, line 138)
Traceback (most recent call last):
  File "C:\xxx\AWSLibrary.py", line 12, in <module>
    import boto3
  File "C:\yyy\Lib\site-packages\boto3\__init__.py", line 16, in <module>
    from boto3.session import Session
  File "C:\yyy\Lib\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\yyy\Lib\site-packages\botocore\session.py", line 38, in <module>
    from botocore import handlers
  File "C:\yyy\Lib\site-packages\botocore\handlers.py", line 25, in <module>
    import uuid
PYTHONPATH:
```

Is there a need to get this external package (that's from 2006), while it is already in the standard lib?

Thank you.

**Comment by tminakov** [comment]
@robooo I'm not sure I understand your intent with the labels on the issue :) 
I mean - I'd be happy to PR a change where the package is not installed, but before that - I've put this up in a ticket for a discussion & triage. You may had a valid need for the external `uuid` that I don't know of, and don't want to take it out. 
Would be happy to hear from you as the lib maintainer.

**Comment by robooo** [comment]
https://hacktoberfest.digitalocean.com/

This was probably because I've started this project from older one (which was for python2 and had this requirement) and probably forget about this to check. I would prefer to use system _uuids_ for sure.
