### ISSUE TITLE
No keyword with name 'Start Consumer Threaded' found

### ISSUE THREAD

**Issue by SenthilNataraj1982** [robooo/robotframework-ConfluentKafkaLibrary#12]
I am new to Kafka , I have installed robotframework==3.2.1 ,robotframework-confluentkafkalibrary==1.5.0-5
confluent-kafka==1.5.0 , while running the examples i am receiving the below error

<img width="633" alt="Screenshot 2020-12-22 at 23 30 54" src="https://user-images.githubusercontent.com/32673725/102942447-4013c300-44ad-11eb-9770-a25017c5a240.png">

<img width="956" alt="Screenshot 2020-12-22 at 23 35 39" src="https://user-images.githubusercontent.com/32673725/102942497-6b96ad80-44ad-11eb-98cf-792013ca8cf9.png">

<img width="596" alt="Screenshot 2020-12-22 at 23 31 38" src="https://user-images.githubusercontent.com/32673725/102946716-60e21580-44b9-11eb-90bd-2238d2cabb1e.png">

<img width="642" alt="Screenshot 2020-12-22 at 23 31 59" src="https://user-images.githubusercontent.com/32673725/102946758-7a835d00-44b9-11eb-97a0-04e735c8db87.png">

Please let me know if I am missing any dependencies. Your help is much appreciated

**Comment by robooo** [comment]
Hi @SenthilNataraj1982, 
please verify it with latest version (-7), just run `pip install robotframework-confluentkafkalibrary` it should be post7.

your setup looks ok!

**Comment by SenthilNataraj1982** [comment]
Hi @robooo , Thanks for your inputs . I have included keywords in resource file . still I am getting the below error Importing test library 'ConfluentKafkaLibrary' failed: ModuleNotFoundError: No module named 'ConfluentKafkaLibrary'
<img width="1236" alt="Screenshot 2020-12-30 at 11 14 36" src="https://user-images.githubusercontent.com/32673725/103348032-b063ab00-4a90-11eb-9827-f70a22d108df.png">
<img width="1179" alt="Screenshot 2020-12-30 at 11 14 48" src="https://user-images.githubusercontent.com/32673725/103348036-b6598c00-4a90-11eb-9928-a0d46e705640.png">
<img width="1227" alt="Screenshot 2020-12-30 at 11 15 21" src="https://user-images.githubusercontent.com/32673725/103348042-beb1c700-4a90-11eb-94cc-30f10a419316.png">

**Comment by SenthilNataraj1982** [comment]
it is working now. thanks
