### ISSUE TITLE
[Question] Does RF-ConfluentKafkaLibrary support header when producing?

### ISSUE THREAD

**Issue by albinsun** [robooo/robotframework-ConfluentKafkaLibrary#25]
Hi, 

Recently I ran into a case which need to specify header when producing, but  I can not find related argument in [document](https://robooo.github.io/robotframework-ConfluentKafkaLibrary/#library-documentation-top).

As title, does RF-ConfluentKafkaLibrary support it or it's there already?

Ref.
1. https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.produce
2. https://robooo.github.io/robotframework-ConfluentKafkaLibrary/#library-documentation-top

**Comment by robooo** [comment]
Most of the functions supports **kwargs
(https://github.com/robooo/robotframework-ConfluentKafkaLibrary/blob/master/src/ConfluentKafkaLibrary/producer.py#L92)
which allows you to include any parameter from
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.produce

So you can try something like this:
```
${headers}=  Create List  ....
# OR
${headers}=  Create Dictionary  ....
Produce  group_id=${PRODUCER_ID}  topic=${topic_name}  headers=${headers}
```
Please test it and let me know if that works, don't forget about:
_The header key must be a string while the value must be binary, unicode or None._

**Comment by albinsun** [comment]
Hi, @robooo 

Tested, it works well.
