### ISSUE TITLE
Accessing Poll results as dictionary

### ISSUE THREAD

**Issue by ZephyrusMB** [robooo/robotframework-ConfluentKafkaLibrary#26]
Hello,
Keyword Poll return type is a list of dictionary which i cannot access using RF keywords or syntax. Here's my case:

I created a consumer, subscribed to a topic and executed a poll. 

`${messages}=  Poll  group_id=${group_id}  max_records=3 `

This returns a list of dictionary and I have some problem accessing the dictionary's values with the keys. What i tried:

1. I can access the values as list  `${messages}[0]`, but not as dictionary `${messages}[0][key]`. **Msg error:** Bytes '${messages}[0]' used with invalid index 'key'. To use '[key]' as a literal value, it needs to be escaped like `'\[key]'`
2. `${dictElem}    Get From Dictionary    ${messages}[0]    key`  **Msg error:** TypeError: byte indices must be integers or slices, not str
3. `Log Dictionary    ${messages}[0]`  **Msg error:**  AttributeError: 'bytes' object has no attribute 'keys'
4. `Convert To Dictionary      ${messages}[0]`  **Msg error:** TypeError: cannot convert dictionary update sequence element #0 to a sequence

**What it works though is this:**

    ${type}    Evaluate  type(${messages}[0])
    Log    ${type} 
    ${value}  Evaluate   ${messages}[0].get("key")

${type} is <class 'dict'>. I then understand that ${messages}[0] is a dictionary but i don't understand why RF don't recognize it as a dictionary. 

Some more infos.
`Log    ${messages}[0]` **gives**  {"key":"vaue","key2":"value","key3":3}
`Log List   ${messages}` **gives**  

List length is 3 and it contains following items:
0: b'{"key":"vaue","key2":"value","key3":3}'
1: b'{"key":"vaue","key2":"value","key3":3}'
2: b'{"key":"vaue","key2":"value","key3":3}'

Thank you very much.

**Comment by robooo** [comment]
Hi @ZephyrusMB,
could you please show me how do you produce data to kafka?

I will look at this tomorrow but three things came up on my mind:
1. please try to use _decode_format_ https://robooo.github.io/robotframework-ConfluentKafkaLibrary/#Poll (then it should be string) or maybe you can try to load it as json (with json lib, json.loads() )
2. The Evaluate looks strange I think it's converted to unicode e.g. `u'xyz'` to RF but in python you should get simple _bytes_:
```
>>> a = b'{"key":"vaue","key2":"value","key3":3}'
>>> print(type(a))
```
So you are trying to read keys from bytes which will not work + even from unicode it doesn't work.

3. you can try convert it to dict with https://robotframework.org/robotframework/latest/libraries/Collections.html#Convert%20To%20Dictionary

Note: if you want to use basic confluent kafka Message object you can set `only_value=False` in  https://robooo.github.io/robotframework-ConfluentKafkaLibrary/#Poll

**Comment by ZephyrusMB** [comment]
Hi @robooo 
Unluckily i have no chance to show you how data to kafka are produced, the test is a read-only so far (if you allow me this expression).

Thank you very much for your help then what I did after your reply is the following:

1.  Decoded the message as utf-8              
2.  Converted the string as Json with [JSONlibrary](https://robotframework-thailand.github.io/robotframework-jsonlibrary/JSONLibrary.html) 
3. Accessed the value inside the JSON

`${messages}=  Poll  group_id=${group_id}  max_records=3  decode_format=utf_8`    
`${json}    Convert String to JSON    ${messages}[0]`
`${jsonValue}    Get value from JSON    ${json}    $.key`

converting the object as a dictionary is the tried N.3 I showed in my previous message, ended up in this error **TypeError: cannot convert dictionary update sequence element #0 to a sequence**

Thank you again for your help, now it is suppose to be much easier to work with the datas as JSON.

**Comment by robooo** [comment]
Example will be in documentation https://github.com/robooo/robotframework-ConfluentKafkaLibrary/pull/27/commits/da3a7f3db2eb19631e0c5748d98baa7edc3598a1
