### ISSUE TITLE
fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory

### ISSUE THREAD

**Issue by annoyingpart** [robooo/robotframework-ConfluentKafkaLibrary#28]
Hello, I would love to try this library, but I have encountered this error during installation fatal error **C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory** and I cannot move with it. I would appreciate any help with it. Thank you. :)

**Comment by robooo** [comment]
Hi @annoyingpart ,
installation from README should work and is tested on linux + github workflows. What kind of OS are you using and what are the installation steps? 

Based on that error message, try to install kafka library first and then retry.

**Comment by annoyingpart** [comment]
Hi @robooo thank you for replay, installing kafka librarary first did not help. However, what helped me was downgrading python from 3.10 to 3.9.
