### ISSUE TITLE
Unable to install robotframework-confluentkafkalibrary on Amazon EC2 graviton instance type

### ISSUE THREAD

**Issue by sairamkakkunoori** [robooo/robotframework-ConfluentKafkaLibrary#33]
Hello everyone,

     I am trying to install **robotframework-confluentkafkalibrary** on Amazon linux EC2 graviton instance type, but installtion is failing with below error. can someone review and help in resolving the issue.

**Note:** we also tried by installing Python development packages, but still no luck.
yum list python3-devel
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
229 packages excluded due to repository priority protections
Installed Packages**python3-devel.aarch64**                                                     3.7.10-1.amzn2.0.1                                                     @amzn2-core

**Python version:** Python 3.7.10

**ERROR;**
Running setup.py install for confluent-kafka: finished with status 'error'
  error: subprocess-exited-with-error

  × Running setup.py install for confluent-kafka did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.7
      creating build/lib.linux-aarch64-3.7/confluent_kafka
      copying src/confluent_kafka/error.py -> build/lib.linux-aarch64-3.7/confluent_kafka
      copying src/confluent_kafka/serializing_producer.py -> build/lib.linux-aarch64-3.7/confluent_kafka
      copying src/confluent_kafka/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka
      copying src/confluent_kafka/deserializing_consumer.py -> build/lib.linux-aarch64-3.7/confluent_kafka
      creating build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/avro.py -> build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/error.py -> build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/json_schema.py -> build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/schema_registry_client.py -> build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      copying src/confluent_kafka/schema_registry/protobuf.py -> build/lib.linux-aarch64-3.7/confluent_kafka/schema_registry
      creating build/lib.linux-aarch64-3.7/confluent_kafka/serialization
      copying src/confluent_kafka/serialization/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka/serialization
      creating build/lib.linux-aarch64-3.7/confluent_kafka/admin
      copying src/confluent_kafka/admin/_acl.py -> build/lib.linux-aarch64-3.7/confluent_kafka/admin
      copying src/confluent_kafka/admin/_resource.py -> build/lib.linux-aarch64-3.7/confluent_kafka/admin
      copying src/confluent_kafka/admin/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka/admin
      copying src/confluent_kafka/admin/_config.py -> build/lib.linux-aarch64-3.7/confluent_kafka/admin
      creating build/lib.linux-aarch64-3.7/confluent_kafka/avro
      copying src/confluent_kafka/avro/error.py -> build/lib.linux-aarch64-3.7/confluent_kafka/avro
      copying src/confluent_kafka/avro/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka/avro
      copying src/confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-aarch64-3.7/confluent_kafka/avro
      copying src/confluent_kafka/avro/load.py -> build/lib.linux-aarch64-3.7/confluent_kafka/avro
      creating build/lib.linux-aarch64-3.7/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-aarch64-3.7/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-aarch64-3.7/confluent_kafka/kafkatest
      copying src/confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-aarch64-3.7/confluent_kafka/kafkatest
      creating build/lib.linux-aarch64-3.7/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-aarch64-3.7/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-aarch64-3.7/confluent_kafka/avro/serializer
      running build_ext
      building 'confluent_kafka.cimpl' extension
      creating build/temp.linux-aarch64-3.7
      creating build/temp.linux-aarch64-3.7/tmp
      creating build/temp.linux-aarch64-3.7/tmp/pip-install-68vas1l2
      creating build/temp.linux-aarch64-3.7/tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6
      creating build/temp.linux-aarch64-3.7/tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6/src
      creating build/temp.linux-aarch64-3.7/tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6/src/confluent_kafka
      creating build/temp.linux-aarch64-3.7/tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6/src/confluent_kafka/src
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -moutline-atomics -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.7m -c /tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6/src/confluent_kafka/src/confluent_kafka.c -o build/temp.linux-aarch64-3.7/tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6/src/confluent_kafka/src/confluent_kafka.o
      In file included from /tmp/pip-install-68vas1l2/confluent-kafka_3fb59b05b078474d8f48cf36fc061fd6/src/confluent_kafka/src/confluent_kafka.c:17:0:
      /tmp/pip-install-68vas1l2/confluent-**kafka_3fb59b05b078474d8f48cf36fc061fd6/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: librdkafka/rdkafka.h: No such file or directory
       #include <librdkafka/rdkafka.h>**
                ^~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> confluent-kafka

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by robooo** [comment]
Hi @sairamkakkunoori,
I'm not familiar with EC2 graviton instance but this looks like simple missing installation of kafka, or wrong / not linked installation. Please try to install it with dependencies, then try this.

And please include your pip install command, if you are installing the latest or some specific version + pip version. 
Thanks!

**Comment by andyjsharp** [comment]
@sairamkakkunoori , I encountered the same, you need to build/install librdkafka prior to installing this library.

```
You'll need the following to build librdkafka too:  gcc git libssl-dev g++ make

git clone https://github.com/edenhill/librdkafka.git
cd librdkafka
git checkout tags/v2.0.2
./configure
make
make install
```

**Comment by robooo** [comment]
Hi @sairamkakkunoori
is it already working with mentioned steps?

**Comment by robooo** [comment]
Closing since there is no response. I linked this issue right into README
https://github.com/robooo/robotframework-ConfluentKafkaLibrary#known-limitations
so the users can find the steps more easily.

Thank you @andyjsharp !
