### ISSUE TITLE
ValueError: Consumer or producer group_id is wrong or does not exists!

### ISSUE THREAD

**Issue by andyjsharp** [robooo/robotframework-ConfluentKafkaLibrary#41]
Running with 2.0.2-3, and trying to check that a topic exists in a given threaded consumer.
We are using Get Thread Group Id and this is returning a value from our threads.  e.g. 

```
Arguments: [ <GetMessagesThread(Thread-2, started daemon 140414778578624)> ]
Return: 'beb1aba9-056e-4877-aca8-403da54b2e4a'
${telemetry_group_id} = beb1aba9-056e-4877-aca8-403da54b2e4a
```

However, when trying to use this with ```List Topics    ${telemetry_group_id}    abc.network.telemetry``` we receive the following output.

```
ValueError: Consumer or producer group_id is wrong or does not exists!	
18:09:04.950	DEBUG	Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ConfluentKafkaLibrary/__init__.py", line 118, in list_topics
    raise ValueError('Consumer or producer group_id is wrong or does not exists!')
ValueError: Consumer or producer group_id is wrong or does not exists!
```

I'm not sure if this is expected behaviour or not, as I can see that threaded consumer group id  is not added to consumers.  So perhaps this is expected, although it would be useful if it were possible to leverage the thread group id for this type of task rather than having to make another consumer just for the purpose of getting topic lists etc.

**Comment by robooo** [comment]
Hi @andyjsharp,
why do you exactly using `List Topics    ${telemetry_group_id}    abc.network.telemetry` instead of just `List Topics    ${telemetry_group_id}` ? 
I can do some testing this weekend and will get back to you

**Comment by andyjsharp** [comment]
@robooo : I just wanted to make sure that a specific topic was present, rather than get all the topics back.  If that makes any sense..?  No rush, don't spoil your w/end just for this.  It's just an observation, not really blocking me on this particular project.

**Comment by robooo** [comment]
@andyjsharp please update to [2.0.2-4](https://github.com/robooo/robotframework-ConfluentKafkaLibrary/releases/tag/2.0.2-4) and try your tests again

**Comment by andyjsharp** [comment]
@robooo : works perfect, many thanks.
